name: Node-Systemd-Service Role CI
on:
  push:
    branches: ["main"]
jobs:
  validate-role:
    runs-on: 'ubuntu-latest'
    container: ghcr.io/curium-rocks/ansible-roles-qa:main
    steps:
    - uses: actions/checkout@v2
    - run: ansible-lint -p tests/test.yml 
    - run: ansible-playbook -i tests/ci tests/test.yml
  publish-role:
    needs: ['validate-role']
    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@v2
    - run: 'echo test'