name: Node-Systemd-Service Role CI
on:
  push:
    branches: ["main"]
    paths: ["curium-rocks/nexus/roles/node-systemd-service/**", ".github/workflows/node-systemd-service.yaml"]
defaults:
  run:
    working-directory: curium-rocks/nexus
jobs:
  validate-role:
    runs-on: 'ubuntu-latest'
    container: ghcr.io/curium-rocks/ansible-roles-qa:main
    steps:
    - uses: actions/checkout@v2
    - run: ansible-lint -p node-systemd-service/tests/test.yml node-systemd-service
      working-directory: curium-rocks/nexus/roles
    - run: ansible-playbook -i node-systemd-service/tests/ci node-systemd-service/tests/test.yml
      working-directory: curium-rocks/nexus/roles
  publish-role:
    needs: ['validate-role']
    runs-on: 'ubuntu-latest'
    env:
      GALAXY_API_TOKEN: ${{ secrets.GALAXY_API_TOKEN }}
    steps:
    - uses: actions/checkout@v2
    - run: ansible-galaxy collection build
    - run: ansible-galaxy collection publish ./curium-rocks-nexus-0.1.0.tar.gz --token $GALAXY_API_TOKEN