name: Node-Systemd-Service Role CI
on:
  push:
    branches: ["main"]
    paths: ["curium_rocks/nexus/roles/node-systemd-service/**", ".github/workflows/node-systemd-service.yaml"]
defaults:
  run:
    working-directory: curium_rocks/nexus
jobs:
  validate-role:
    runs-on: 'ubuntu-latest'
    container: ghcr.io/curium-rocks/ansible-roles-qa:main
    steps:
    - uses: actions/checkout@v2
    - run: ansible-lint -p roles/node-systemd-service/tests/test.yml roles/node-systemd-service
    - run: ansible-playbook -i roles/node-systemd-service/tests/ci roles/node-systemd-service/tests/test.yml
  publish-role:
    needs: ['validate-role']
    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@v2
    - run: ansible-galaxy collection build