name: Node-Systemd-Service Role CI
on:
  push:
    paths:
      - 'bryopsida/nexus/**/*'
      - '.github/workflows/node-systemd-service.yaml'
defaults:
  run:
    working-directory: bryopsida/nexus
jobs:
  validate-role:
    runs-on: 'ubuntu-latest'
    container: ghcr.io/curium-rocks/ansible-roles-qa:main
    steps:
    - uses: actions/checkout@v3
    - run: ansible-lint -p node_systemd_service/tests/test.yml node_systemd_service
      working-directory: bryopsida/nexus/roles
    - run: ansible-playbook -i node_systemd_service/tests/ci node_systemd_service/tests/test.yml
      working-directory: bryopsida/nexus/roles
    - run: |
        ansible-playbook -i node_systemd_service/tests/ci node_systemd_service/tests/test.yml --extra-vars "node_version=v16.9.1"
        export OBSV_NVM_VER=$(cat /opt/curium/systemd-node-service/.nvmrc)
        if [ "$OBSV_NVM_VER" != "v16.9.1" ]; then 
          echo "Unexpected node version $OBSV_NVM_VER"
          exit 1
        fi
      working-directory: bryopsida/nexus/roles
  publish-role:
    needs: ['validate-role']
    if: github.ref == 'refs/heads/main'
    runs-on: 'ubuntu-latest'
    env:
      GALAXY_API_TOKEN: ${{ secrets.GALAXY_API_TOKEN }}
    steps:
    - uses: actions/checkout@v3
    - run: ansible-galaxy collection build
    - run: ansible-galaxy collection publish ./bryopsida-nexus-0.2.0.tar.gz --token $GALAXY_API_TOKEN