name: Node-Systemd-Service Role CI
on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths: 
      - "bryopsida/nexus/roles/node_systemd_service/**"
      - "./.github/workflows/node_systemd_service.yaml"
defaults:
  run:
    working-directory: bryopsida/nexus
jobs:
  validate-role:
    runs-on: 'ubuntu-latest'
    container: ghcr.io/curium-rocks/ansible-roles-qa:main
    steps:
    - uses: actions/checkout@v2
    - run: ansible-lint -p node_systemd_service/tests/test.yml node_systemd_service
      working-directory: bryopsida/nexus/roles
    - run: ansible-playbook -i node_systemd_service/tests/ci node_systemd_service/tests/test.yml
      working-directory: bryopsida/nexus/roles
  publish-role:
    needs: ['validate-role']
    runs-on: 'ubuntu-latest'
    env:
      GALAXY_API_TOKEN: ${{ secrets.GALAXY_API_TOKEN }}
    steps:
    - uses: actions/checkout@v2
    - run: ansible-galaxy collection build
    - run: ansible-galaxy collection publish ./bryopsida-nexus-0.1.0.tar.gz --token $GALAXY_API_TOKEN